/*
 * client_api API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.client.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vcita.client.client.model.PortalsBusinessUidShareDocumentsFormSubmitFormData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineObject1
 */
public class InlineObject1Test {
    private final InlineObject1 model = new InlineObject1();

    /**
     * Model tests for InlineObject1
     */
    @Test
    public void testInlineObject1() {
        // TODO: test InlineObject1
    }

    /**
     * Test the property 'formData'
     */
    @Test
    public void formDataTest() {
        // TODO: test formData
    }

}
