/*
 * client_api API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.client.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PortalsBusinessUidContactSubmitSourceData
 */
public class PortalsBusinessUidContactSubmitSourceDataTest {
    private final PortalsBusinessUidContactSubmitSourceData model = new PortalsBusinessUidContactSubmitSourceData();

    /**
     * Model tests for PortalsBusinessUidContactSubmitSourceData
     */
    @Test
    public void testPortalsBusinessUidContactSubmitSourceData() {
        // TODO: test PortalsBusinessUidContactSubmitSourceData
    }

    /**
     * Test the property 'isWidget'
     */
    @Test
    public void isWidgetTest() {
        // TODO: test isWidget
    }

    /**
     * Test the property 'o'
     */
    @Test
    public void oTest() {
        // TODO: test o
    }

    /**
     * Test the property 's'
     */
    @Test
    public void sTest() {
        // TODO: test s
    }

    /**
     * Test the property 'topUrl'
     */
    @Test
    public void topUrlTest() {
        // TODO: test topUrl
    }

}
