/*
 * client_api API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.client.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vcita.client.client.model.PortalsBusinessUidShareDocumentsFormSubmitFields;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PortalsBusinessUidShareDocumentsFormSubmitFormData
 */
public class PortalsBusinessUidShareDocumentsFormSubmitFormDataTest {
    private final PortalsBusinessUidShareDocumentsFormSubmitFormData model = new PortalsBusinessUidShareDocumentsFormSubmitFormData();

    /**
     * Model tests for PortalsBusinessUidShareDocumentsFormSubmitFormData
     */
    @Test
    public void testPortalsBusinessUidShareDocumentsFormSubmitFormData() {
        // TODO: test PortalsBusinessUidShareDocumentsFormSubmitFormData
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

}
