/*
 * client_api API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.client.client.api;

import com.vcita.client.client.ApiCallback;
import com.vcita.client.client.ApiClient;
import com.vcita.client.client.ApiException;
import com.vcita.client.client.ApiResponse;
import com.vcita.client.client.Configuration;
import com.vcita.client.client.Pair;
import com.vcita.client.client.ProgressRequestBody;
import com.vcita.client.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.vcita.client.client.model.InlineObject;
import com.vcita.client.client.model.PortalsBusinessUidContactGetFormGet200Response;
import com.vcita.client.client.model.PortalsBusinessUidContactSubmitPost200Response;
import com.vcita.client.client.model.PortalsBusinessUidShareDocumentsFormGetFormGet200Response;
import com.vcita.client.client.model.PortalsBusinessUidShareDocumentsFormSubmitFormData;
import com.vcita.client.client.model.PortalsBusinessUidShareDocumentsFormSubmitPost200Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class FormsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public FormsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public FormsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for portalsBusinessUidContactGetFormGet
     * @param businessUid business_uid (required)
     * @param authorization API Token. The resulting header should look like this: &#39;Authorization: \&quot;Bearer API_TOKEN\&quot;&#39; (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call portalsBusinessUidContactGetFormGetCall(String businessUid, String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/portals/{business_uid}/contact/get_form"
            .replaceAll("\\{" + "business_uid" + "\\}", localVarApiClient.escapeString(businessUid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "default" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call portalsBusinessUidContactGetFormGetValidateBeforeCall(String businessUid, String authorization, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'businessUid' is set
        if (businessUid == null) {
            throw new ApiException("Missing the required parameter 'businessUid' when calling portalsBusinessUidContactGetFormGet(Async)");
        }
        
        // verify the required parameter 'authorization' is set
        if (authorization == null) {
            throw new ApiException("Missing the required parameter 'authorization' when calling portalsBusinessUidContactGetFormGet(Async)");
        }
        

        okhttp3.Call localVarCall = portalsBusinessUidContactGetFormGetCall(businessUid, authorization, _callback);
        return localVarCall;

    }

    /**
     * Get Leave Details Form
     * Gets the leave details form of the business.
     * @param businessUid business_uid (required)
     * @param authorization API Token. The resulting header should look like this: &#39;Authorization: \&quot;Bearer API_TOKEN\&quot;&#39; (required)
     * @return PortalsBusinessUidContactGetFormGet200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public PortalsBusinessUidContactGetFormGet200Response portalsBusinessUidContactGetFormGet(String businessUid, String authorization) throws ApiException {
        ApiResponse<PortalsBusinessUidContactGetFormGet200Response> localVarResp = portalsBusinessUidContactGetFormGetWithHttpInfo(businessUid, authorization);
        return localVarResp.getData();
    }

    /**
     * Get Leave Details Form
     * Gets the leave details form of the business.
     * @param businessUid business_uid (required)
     * @param authorization API Token. The resulting header should look like this: &#39;Authorization: \&quot;Bearer API_TOKEN\&quot;&#39; (required)
     * @return ApiResponse&lt;PortalsBusinessUidContactGetFormGet200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PortalsBusinessUidContactGetFormGet200Response> portalsBusinessUidContactGetFormGetWithHttpInfo(String businessUid, String authorization) throws ApiException {
        okhttp3.Call localVarCall = portalsBusinessUidContactGetFormGetValidateBeforeCall(businessUid, authorization, null);
        try {
            Type localVarReturnType = new TypeToken<PortalsBusinessUidContactGetFormGet200Response>(){}.getType();
            return localVarApiClient.execute(localVarCall, localVarReturnType);
        } catch (ApiException e) {
            e.setErrorObject(localVarApiClient.getJSON().getGson().fromJson(e.getResponseBody(), new TypeToken<PortalsBusinessUidContactGetFormGet200Response>(){}.getType()));
            e.setErrorObjectType(new GenericType<PortalsBusinessUidContactGetFormGet200Response>(){});
            throw e;
        }
    }

    /**
     * Get Leave Details Form (asynchronously)
     * Gets the leave details form of the business.
     * @param businessUid business_uid (required)
     * @param authorization API Token. The resulting header should look like this: &#39;Authorization: \&quot;Bearer API_TOKEN\&quot;&#39; (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call portalsBusinessUidContactGetFormGetAsync(String businessUid, String authorization, final ApiCallback<PortalsBusinessUidContactGetFormGet200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = portalsBusinessUidContactGetFormGetValidateBeforeCall(businessUid, authorization, _callback);
        Type localVarReturnType = new TypeToken<PortalsBusinessUidContactGetFormGet200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for portalsBusinessUidContactSubmitPost
     * @param businessUid business_uid (required)
     * @param authorization API Token. The resulting header should look like this: &#39;Authorization: \&quot;Bearer API_TOKEN\&quot;&#39; (required)
     * @param inlineObject  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call portalsBusinessUidContactSubmitPostCall(String businessUid, String authorization, InlineObject inlineObject, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = inlineObject;

        // create path and map variables
        String localVarPath = "/portals/{business_uid}/contact/submit"
            .replaceAll("\\{" + "business_uid" + "\\}", localVarApiClient.escapeString(businessUid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "default" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call portalsBusinessUidContactSubmitPostValidateBeforeCall(String businessUid, String authorization, InlineObject inlineObject, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'businessUid' is set
        if (businessUid == null) {
            throw new ApiException("Missing the required parameter 'businessUid' when calling portalsBusinessUidContactSubmitPost(Async)");
        }
        
        // verify the required parameter 'authorization' is set
        if (authorization == null) {
            throw new ApiException("Missing the required parameter 'authorization' when calling portalsBusinessUidContactSubmitPost(Async)");
        }
        

        okhttp3.Call localVarCall = portalsBusinessUidContactSubmitPostCall(businessUid, authorization, inlineObject, _callback);
        return localVarCall;

    }

    /**
     * Submits Leave Details Form
     * Submits Leave Details Form to the business.
     * @param businessUid business_uid (required)
     * @param authorization API Token. The resulting header should look like this: &#39;Authorization: \&quot;Bearer API_TOKEN\&quot;&#39; (required)
     * @param inlineObject  (optional)
     * @return PortalsBusinessUidContactSubmitPost200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public PortalsBusinessUidContactSubmitPost200Response portalsBusinessUidContactSubmitPost(String businessUid, String authorization, InlineObject inlineObject) throws ApiException {
        ApiResponse<PortalsBusinessUidContactSubmitPost200Response> localVarResp = portalsBusinessUidContactSubmitPostWithHttpInfo(businessUid, authorization, inlineObject);
        return localVarResp.getData();
    }

    /**
     * Submits Leave Details Form
     * Submits Leave Details Form to the business.
     * @param businessUid business_uid (required)
     * @param authorization API Token. The resulting header should look like this: &#39;Authorization: \&quot;Bearer API_TOKEN\&quot;&#39; (required)
     * @param inlineObject  (optional)
     * @return ApiResponse&lt;PortalsBusinessUidContactSubmitPost200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PortalsBusinessUidContactSubmitPost200Response> portalsBusinessUidContactSubmitPostWithHttpInfo(String businessUid, String authorization, InlineObject inlineObject) throws ApiException {
        okhttp3.Call localVarCall = portalsBusinessUidContactSubmitPostValidateBeforeCall(businessUid, authorization, inlineObject, null);
        try {
            Type localVarReturnType = new TypeToken<PortalsBusinessUidContactSubmitPost200Response>(){}.getType();
            return localVarApiClient.execute(localVarCall, localVarReturnType);
        } catch (ApiException e) {
            e.setErrorObject(localVarApiClient.getJSON().getGson().fromJson(e.getResponseBody(), new TypeToken<PortalsBusinessUidContactSubmitPost200Response>(){}.getType()));
            e.setErrorObjectType(new GenericType<PortalsBusinessUidContactSubmitPost200Response>(){});
            throw e;
        }
    }

    /**
     * Submits Leave Details Form (asynchronously)
     * Submits Leave Details Form to the business.
     * @param businessUid business_uid (required)
     * @param authorization API Token. The resulting header should look like this: &#39;Authorization: \&quot;Bearer API_TOKEN\&quot;&#39; (required)
     * @param inlineObject  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call portalsBusinessUidContactSubmitPostAsync(String businessUid, String authorization, InlineObject inlineObject, final ApiCallback<PortalsBusinessUidContactSubmitPost200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = portalsBusinessUidContactSubmitPostValidateBeforeCall(businessUid, authorization, inlineObject, _callback);
        Type localVarReturnType = new TypeToken<PortalsBusinessUidContactSubmitPost200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for portalsBusinessUidShareDocumentsFormGetFormGet
     * @param authorization API Token. The resulting header should look like this: &#39;Authorization: \&quot;Bearer API_TOKEN\&quot;&#39; (required)
     * @param businessUid  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Share Documents Form </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call portalsBusinessUidShareDocumentsFormGetFormGetCall(String authorization, String businessUid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/portals/{business_uid}/share_documents_form/get_form"
            .replaceAll("\\{" + "business_uid" + "\\}", localVarApiClient.escapeString(businessUid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "default" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call portalsBusinessUidShareDocumentsFormGetFormGetValidateBeforeCall(String authorization, String businessUid, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'authorization' is set
        if (authorization == null) {
            throw new ApiException("Missing the required parameter 'authorization' when calling portalsBusinessUidShareDocumentsFormGetFormGet(Async)");
        }
        
        // verify the required parameter 'businessUid' is set
        if (businessUid == null) {
            throw new ApiException("Missing the required parameter 'businessUid' when calling portalsBusinessUidShareDocumentsFormGetFormGet(Async)");
        }
        

        okhttp3.Call localVarCall = portalsBusinessUidShareDocumentsFormGetFormGetCall(authorization, businessUid, _callback);
        return localVarCall;

    }

    /**
     * Get Share Documents Form
     * Gets the share documents form of the business.
     * @param authorization API Token. The resulting header should look like this: &#39;Authorization: \&quot;Bearer API_TOKEN\&quot;&#39; (required)
     * @param businessUid  (required)
     * @return PortalsBusinessUidShareDocumentsFormGetFormGet200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Share Documents Form </td><td>  -  </td></tr>
     </table>
     */
    public PortalsBusinessUidShareDocumentsFormGetFormGet200Response portalsBusinessUidShareDocumentsFormGetFormGet(String authorization, String businessUid) throws ApiException {
        ApiResponse<PortalsBusinessUidShareDocumentsFormGetFormGet200Response> localVarResp = portalsBusinessUidShareDocumentsFormGetFormGetWithHttpInfo(authorization, businessUid);
        return localVarResp.getData();
    }

    /**
     * Get Share Documents Form
     * Gets the share documents form of the business.
     * @param authorization API Token. The resulting header should look like this: &#39;Authorization: \&quot;Bearer API_TOKEN\&quot;&#39; (required)
     * @param businessUid  (required)
     * @return ApiResponse&lt;PortalsBusinessUidShareDocumentsFormGetFormGet200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Share Documents Form </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PortalsBusinessUidShareDocumentsFormGetFormGet200Response> portalsBusinessUidShareDocumentsFormGetFormGetWithHttpInfo(String authorization, String businessUid) throws ApiException {
        okhttp3.Call localVarCall = portalsBusinessUidShareDocumentsFormGetFormGetValidateBeforeCall(authorization, businessUid, null);
        try {
            Type localVarReturnType = new TypeToken<PortalsBusinessUidShareDocumentsFormGetFormGet200Response>(){}.getType();
            return localVarApiClient.execute(localVarCall, localVarReturnType);
        } catch (ApiException e) {
            e.setErrorObject(localVarApiClient.getJSON().getGson().fromJson(e.getResponseBody(), new TypeToken<PortalsBusinessUidShareDocumentsFormGetFormGet200Response>(){}.getType()));
            e.setErrorObjectType(new GenericType<PortalsBusinessUidShareDocumentsFormGetFormGet200Response>(){});
            throw e;
        }
    }

    /**
     * Get Share Documents Form (asynchronously)
     * Gets the share documents form of the business.
     * @param authorization API Token. The resulting header should look like this: &#39;Authorization: \&quot;Bearer API_TOKEN\&quot;&#39; (required)
     * @param businessUid  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Share Documents Form </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call portalsBusinessUidShareDocumentsFormGetFormGetAsync(String authorization, String businessUid, final ApiCallback<PortalsBusinessUidShareDocumentsFormGetFormGet200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = portalsBusinessUidShareDocumentsFormGetFormGetValidateBeforeCall(authorization, businessUid, _callback);
        Type localVarReturnType = new TypeToken<PortalsBusinessUidShareDocumentsFormGetFormGet200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for portalsBusinessUidShareDocumentsFormSubmitPost
     * @param authorization API Token. The resulting header should look like this: &#39;Authorization: \&quot;Bearer API_TOKEN\&quot;&#39; (required)
     * @param businessUid  (required)
     * @param formData  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Share Documents Form </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call portalsBusinessUidShareDocumentsFormSubmitPostCall(String authorization, String businessUid, List<PortalsBusinessUidShareDocumentsFormSubmitFormData> formData, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/portals/{business_uid}/share_documents_form/submit"
            .replaceAll("\\{" + "business_uid" + "\\}", localVarApiClient.escapeString(businessUid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (formData != null) {
            localVarFormParams.put("form_data", formData);
        }

        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "multipart/form-data"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "default" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call portalsBusinessUidShareDocumentsFormSubmitPostValidateBeforeCall(String authorization, String businessUid, List<PortalsBusinessUidShareDocumentsFormSubmitFormData> formData, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'authorization' is set
        if (authorization == null) {
            throw new ApiException("Missing the required parameter 'authorization' when calling portalsBusinessUidShareDocumentsFormSubmitPost(Async)");
        }
        
        // verify the required parameter 'businessUid' is set
        if (businessUid == null) {
            throw new ApiException("Missing the required parameter 'businessUid' when calling portalsBusinessUidShareDocumentsFormSubmitPost(Async)");
        }
        

        okhttp3.Call localVarCall = portalsBusinessUidShareDocumentsFormSubmitPostCall(authorization, businessUid, formData, _callback);
        return localVarCall;

    }

    /**
     * Submits Share Documents Form
     * Submits Share Documents Form to the business.
     * @param authorization API Token. The resulting header should look like this: &#39;Authorization: \&quot;Bearer API_TOKEN\&quot;&#39; (required)
     * @param businessUid  (required)
     * @param formData  (optional)
     * @return PortalsBusinessUidShareDocumentsFormSubmitPost200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Share Documents Form </td><td>  -  </td></tr>
     </table>
     */
    public PortalsBusinessUidShareDocumentsFormSubmitPost200Response portalsBusinessUidShareDocumentsFormSubmitPost(String authorization, String businessUid, List<PortalsBusinessUidShareDocumentsFormSubmitFormData> formData) throws ApiException {
        ApiResponse<PortalsBusinessUidShareDocumentsFormSubmitPost200Response> localVarResp = portalsBusinessUidShareDocumentsFormSubmitPostWithHttpInfo(authorization, businessUid, formData);
        return localVarResp.getData();
    }

    /**
     * Submits Share Documents Form
     * Submits Share Documents Form to the business.
     * @param authorization API Token. The resulting header should look like this: &#39;Authorization: \&quot;Bearer API_TOKEN\&quot;&#39; (required)
     * @param businessUid  (required)
     * @param formData  (optional)
     * @return ApiResponse&lt;PortalsBusinessUidShareDocumentsFormSubmitPost200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Share Documents Form </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PortalsBusinessUidShareDocumentsFormSubmitPost200Response> portalsBusinessUidShareDocumentsFormSubmitPostWithHttpInfo(String authorization, String businessUid, List<PortalsBusinessUidShareDocumentsFormSubmitFormData> formData) throws ApiException {
        okhttp3.Call localVarCall = portalsBusinessUidShareDocumentsFormSubmitPostValidateBeforeCall(authorization, businessUid, formData, null);
        try {
            Type localVarReturnType = new TypeToken<PortalsBusinessUidShareDocumentsFormSubmitPost200Response>(){}.getType();
            return localVarApiClient.execute(localVarCall, localVarReturnType);
        } catch (ApiException e) {
            e.setErrorObject(localVarApiClient.getJSON().getGson().fromJson(e.getResponseBody(), new TypeToken<PortalsBusinessUidShareDocumentsFormSubmitPost200Response>(){}.getType()));
            e.setErrorObjectType(new GenericType<PortalsBusinessUidShareDocumentsFormSubmitPost200Response>(){});
            throw e;
        }
    }

    /**
     * Submits Share Documents Form (asynchronously)
     * Submits Share Documents Form to the business.
     * @param authorization API Token. The resulting header should look like this: &#39;Authorization: \&quot;Bearer API_TOKEN\&quot;&#39; (required)
     * @param businessUid  (required)
     * @param formData  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Share Documents Form </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call portalsBusinessUidShareDocumentsFormSubmitPostAsync(String authorization, String businessUid, List<PortalsBusinessUidShareDocumentsFormSubmitFormData> formData, final ApiCallback<PortalsBusinessUidShareDocumentsFormSubmitPost200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = portalsBusinessUidShareDocumentsFormSubmitPostValidateBeforeCall(authorization, businessUid, formData, _callback);
        Type localVarReturnType = new TypeToken<PortalsBusinessUidShareDocumentsFormSubmitPost200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
