/*
 * client_api API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vcita.client.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.vcita.client.client.JSON;

/**
 * PortalsBusinessUidShareDocumentsFormSubmitFields
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PortalsBusinessUidShareDocumentsFormSubmitFields {
  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  private Object key;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private Object value;

  public PortalsBusinessUidShareDocumentsFormSubmitFields() { 
  }

  public PortalsBusinessUidShareDocumentsFormSubmitFields key(Object key) {
    
    this.key = key;
    return this;
  }

   /**
   * Field Id(string), file(array), o/s(string)
   * @return key
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Field Id(string), file(array), o/s(string)")

  public Object getKey() {
    return key;
  }


  public void setKey(Object key) {
    this.key = key;
  }


  public PortalsBusinessUidShareDocumentsFormSubmitFields value(Object value) {
    
    this.value = value;
    return this;
  }

   /**
   * Field Value(string), files(binary), source(string)
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Field Value(string), files(binary), source(string)")

  public Object getValue() {
    return value;
  }


  public void setValue(Object value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PortalsBusinessUidShareDocumentsFormSubmitFields portalsBusinessUidShareDocumentsFormSubmitFields = (PortalsBusinessUidShareDocumentsFormSubmitFields) o;
    return Objects.equals(this.key, portalsBusinessUidShareDocumentsFormSubmitFields.key) &&
        Objects.equals(this.value, portalsBusinessUidShareDocumentsFormSubmitFields.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PortalsBusinessUidShareDocumentsFormSubmitFields {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("key");
    openapiFields.add("value");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PortalsBusinessUidShareDocumentsFormSubmitFields
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (PortalsBusinessUidShareDocumentsFormSubmitFields.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in PortalsBusinessUidShareDocumentsFormSubmitFields is not found in the empty JSON string", PortalsBusinessUidShareDocumentsFormSubmitFields.openapiRequiredFields.toString()));
        }
      }
      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!PortalsBusinessUidShareDocumentsFormSubmitFields.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PortalsBusinessUidShareDocumentsFormSubmitFields` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PortalsBusinessUidShareDocumentsFormSubmitFields.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PortalsBusinessUidShareDocumentsFormSubmitFields' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PortalsBusinessUidShareDocumentsFormSubmitFields> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PortalsBusinessUidShareDocumentsFormSubmitFields.class));

       return (TypeAdapter<T>) new TypeAdapter<PortalsBusinessUidShareDocumentsFormSubmitFields>() {
           @Override
           public void write(JsonWriter out, PortalsBusinessUidShareDocumentsFormSubmitFields value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PortalsBusinessUidShareDocumentsFormSubmitFields read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PortalsBusinessUidShareDocumentsFormSubmitFields given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PortalsBusinessUidShareDocumentsFormSubmitFields
  * @throws IOException if the JSON string is invalid with respect to PortalsBusinessUidShareDocumentsFormSubmitFields
  */
  public static PortalsBusinessUidShareDocumentsFormSubmitFields fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PortalsBusinessUidShareDocumentsFormSubmitFields.class);
  }

 /**
  * Convert an instance of PortalsBusinessUidShareDocumentsFormSubmitFields to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

